seed: 1
work_dir: ./exp/h2o
run_mode: test

# feeder
feeder: feeders.feeder_h2o.Feeder_Test
train_feeder_args:
  data_path: data/h2o/h2o_pth
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 120
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False
  entity_rearrangement: False
  use_rgb: True

test_feeder_args:
  data_path: data/h2o/h2o_pth
  split: test
  debug: False
  window_size: 120
  p_interval: [0.95]
  vel: False
  bone: False
  use_rgb: True

# model
model: model.ISTANet.Model
model_args:
  window_size: [20, 1, 3]
  num_frames: 120
  num_joints: 21
  num_persons: 3
  num_channels: 3
  num_classes: 36
  num_objs: 8
  num_verbs: 11
  num_heads: 4
  kernel_size: [3, 5]
  use_pes: True
  config: [[64,  64,  16], [64,  64,  16], 
           [64,  128, 32], [128, 128, 32],
           [128, 256, 64], [256, 256, 64], 
           [256, 256, 64], [256, 256, 64]]

#optim
optimizer: SGD
weight_decay: 0.0001
base_lr: 1.e-2
lr_decay_rate: 0.5
step: [20, 40, 60, 80, 100]
warm_up_epoch: 5
nesterov: True

# loss
loss: LabelSmoothingCrossEntropy
loss_args:
  smoothing: 0.05
  temperature: 1.0

noun_loss_weight: 1.5
verb_loss_weight: 1
action_loss_weight: 1
feat_loss_weight: 1.2

# training
device: [0]
cuda_visible_device: '0'
batch_size: 4
test_batch_size: 4
num_epoch: 120

